### ISSUE TITLE
T-TWR Plus issue with a rl78/g1m

### ISSUE THREAD

**Issue by lotrdocker** [OpenRTX/sa8x8-fw#14]
Hello,

I try to install the firmware to a T-TWR Plus device with a rl78/g1m. I followed the procedure. The device rl78/g1m is well recognized with the command "dmesg" but, on my computer, the device /dev/ttyUSB0 is not present, so the command "rl78flash -i /dev/ttyUSB0 -m 1 -a sa8x8-fw-sa868s-uhf.s37 -v" could not work.

Any idea ?

Regards.

Stéphane, F5UGQ.

**Comment by lotrdocker** [comment]
Hello,

I did some more tests. I'm using the schematic above without the UART_VCC connected, the T-TWR is supplied with USB, if I connect UART_VCC, 3.3V, the T-TWR is not supplied.

UART_GND o-------------o T-TWR_RG
UART_VCC o-------------o T-TWR_RV (do not connect when supplying the device over USB!)
UART_RX  o---------+---o T-TWR_RT
UART_TX  o----|<|--/
UART_RTS o----|<|------o T-TWR_RR

The ACT led of the rl78/g1m is illuminated, so, according to the documentation, connected to The T-TWR and the T-TWR is seen as device /dev/ttyACM0. I fixed the baud rate of the device  /dev/ttyACM0 to 115200 with the command "stty -F /dev/ttyACM0 115200".

I executed the command "rl78flash -i /dev/ttyACM0 -m 3 -a sa8x8-fw-sa868s-uhf.s37 -v" but this error occur:
_**rl78flash v0.7.0
FAILED baud rate set
Initialization failed**_

**Comment by edgetriggered** [comment]
Can you please provide more information about the RL78/G1M? I have not encountered an SA868S with one before. This firmware was designed for modules using the R5F1026A, which is RL78/G12 family.
