### ISSUE TITLE
Wrong way to write in readme file

### ISSUE THREAD

**Issue by lewisxhe** [OpenRTX/sa8x8-fw#16]
If you write like this in the [README](https://github.com/OpenRTX/sa8x8-fw#firmware-flashing), an out-of-execution order error will occur. It is the same regardless of win or liunx. Please change it.

![image](https://github.com/OpenRTX/sa8x8-fw/assets/22990954/31ffd334-4ff3-4ef7-bc5c-a72826574267)

If I'm wrong, please close the issue

**Comment by edgetriggered** [comment]
Thanks, I have updated the documentation with your recommendation.
