### ISSUE TITLE
Detail on Programming Connections

### ISSUE THREAD

**Issue by darksidelemm** [OpenRTX/sa8x8-fw#5]
Hi, some more detail on the connections required to flash up an Open-edition SA868 would be appreciated.
In particular:

* The pinout of the programming pads on the underside of the SA868 module.
* The [diagram linked to](https://github.com/msalau/rl78flash/blob/master/hw/rl78s-hw.png) in the README.md shows 4 different 'modes' for programming - which one was used?
* Logic levels required for programming, and what other connections must be made.

Thanks!

**Comment by edgetriggered** [comment]
I added some additional notes about the programming interface. Please close the issue if you find the updates adequate.

**Comment by darksidelemm** [comment]
It's a little difficult to read the names of the pins in [the mode diagrams](https://github.com/msalau/rl78flash/blob/master/hw/rl78s-hw.png), I'm guessing that the 'TOOL<something i can't read>40' pin is the 'MODE' pin you've got marked out?

**Comment by edgetriggered** [comment]
That's right, I think the diagram shows TOOL0/P40 and corresponds to a bidirectional serial pin used for programming on the internal RL78 microcontroller. I updated the pinout to reflect this. Previous versions of the modules used a different microcontroller family which called this pin MODE instead.

**Comment by darksidelemm** [comment]
OK, no problems. All good, thanks for the added information!
Now to sort out some kind of pogo-pin board to give this a go!

**Comment by darksidelemm** [comment]
Found these on aliexpress: https://www.aliexpress.com/item/4001016625881.html
Might be handy to link to something like that as a recommendation for programming?

**Comment by edgetriggered** [comment]
I found a similar one early on but haven't tried one to have a recommendation. As soon as it has been fabricated and tested, I will share my programmer design.

![image](https://github.com/OpenRTX/sa8x8-fw/assets/110491646/57ae79b7-9afd-48e7-9b6a-7ee73b33727b)

**Comment by darksidelemm** [comment]
That looks great!

**Comment by darksidelemm** [comment]
I ended up bodging something up on some veroboard:

![PXL_20230728_040708224](https://github.com/OpenRTX/sa8x8-fw/assets/1040275/15495a04-f8bd-4d0d-928c-e2edbfec5d88)
![sa868_programmer_jig](https://github.com/OpenRTX/sa8x8-fw/assets/1040275/cfe568cf-0566-4e0b-aab9-4c4ba9070c18)

Seems to program fine! Now I need to make up a board to attach these modules to for further testing!
